context/UserContext.tsx, hooks/useUserContext.tsx, pages/_app.tsx, pages/search.tsx
* retrieve cookies on `_app.tsx` instead of `UserContext` 
* set initial userState value to cookies
* set cookies value to userState on init
=> fix: set initital cookies on _app.tsx

.env.development, helpers/_cookies.tsx, pages/search.tsx
No issue present
Two fix in this PR:
1_ When searching and fetching results from server (i.e. reload page), the `adultContentFilter` value was grab using the `splitCookies` function which return different results in different browsers (Safari was not grabbing just the value, but also the cookie name). 
Is not simplified, taking the cookie value directly from Nextjs req object.
2_ On development mode, nodejs is unable verifies the certificate with the CA. This problem doesn't occur on production since we handle Server Certificate and Https. 
A unsecure fix and therefor to be used just in development, is to set …
=> fix: adultContentFilter, add NODE_TLS_REJECT_UNAUTHORIZED

components/Forms/Settings/SettingsForm.tsx
=> fix: assign adult content filter value starting counting form 0

.env.development, __mocks__/mockapiServer.js
=> Fix mock api cors errors

pages/_document.tsx
=> Remove unused code

.env.development
Adding https to the NEXT_PUBLIC_API_URL as expected by the API Server
development enviroment
search page
run web app in local, make a search. Now error should occur and you should be able to see the results page
=> fix: add https to local api url

components/Buttons/ButtonAddToBrowser.tsx
=> fix: chrome add to browser

components/Hero/Hero.module.css, i18n.js, pages/new-about.tsx
=> change to getinitialprops, add loading, hero subtitle

components/Forms/Contact/ContactForm.tsx, pages/new-about.tsx
=> fix: contact form message field name

.stylelintrc.json, components/Hero/Hero.module.css, components/Person/Person.tsx, components/Sliders/ProjectSliders.module.css, components/Sliders/ProjectSliders.tsx
=> fix: new about: slides arrows css order, image height, hero opacity

components/Buttons/Button.tsx, components/Buttons/ButtonOutline/ButtonOutline.tsx, components/Person/Person.module.css, components/Person/Person.tsx, components/Sliders/ProjectSliders.module.css, components/Sliders/ProjectSliders.tsx, pages/new-about.tsx, styles/base.css
=> fix for mobile people links and image, slides

pages/new-about.tsx
=> fix: open new tab opensource link

helpers/_cookies.tsx, hooks/useUserStateSyncedWithCookies.tsx, pages/_app.tsx, pages/search.tsx
=> fix: handle NaN value for adult filter cookies

components/Nav/Nav.tsx
- Quickfix for #51 
#51 
Update blog link to ('https://medium.com/@elliotforwater') in Nav component.
- Nav 
=> Update Blog link in navigation

components/Footer/Footer.module.css, components/Footer/Footer.tsx
Adding phone number to footer for legal prupose
Footer
=> Add: Legal phone number to footer

pages/search.tsx
=> custom error message for search page

pages/search.tsx
=> custom error message for search page (#90)

helpers/_httpExpress.tsx
=> fix: try allow orgin

.env.development.example, .env.staging, helpers/_httpExpress.tsx
=> Serach page cors fix

helpers/_httpExpress.tsx, pages/search.tsx
=> fix: undefined adultcontentfilter

helpers/_httpExpress.tsx, pages/_app.tsx, pages/search.tsx
=> [core]: add console log for staging

helpers/_httpExpress.tsx, pages/_app.tsx
=> Other consolelog for staging

helpers/_httpExpress.tsx, pages/_app.tsx, pages/search.tsx
=> fix: clear staging logs

helpers/_cookies.tsx, pages/_app.test.tsx, pages/_app.tsx, pages/search.tsx
=> fix: adult filter on server req

helpers/_cookies.tsx, pages/_app.test.tsx, pages/_app.tsx, pages/search.tsx
* fix adult filter on server req
* fix tets
=> fix: adult filter on server req (#101)

appConfig.js, pages/api/searchresults/[type].js, pages/search.tsx
=> fix: restore load more button (#105)

pages/search.tsx
=> Fix: map bug

pages/search.tsx
=> fix map bug (#107)

.env.staging, package.json
=> fix: change env for staging

components/AllResultsView/ImagesBlock.tsx, pages/search.tsx
=> fix: link to image under images carousel in 'All' view

components/AllResultsView/ImagesBlock.tsx, pages/search.tsx
=> fix: links to image tab in all view (#114)

components/Layout/Layout.tsx
=> Merge Develop

components/Layout/Layout.tsx, package-lock.json, package.json, pages/404.tsx, pages/search.tsx
=> Fix: Add robot nofollow to search template

README.md
There wasn't an issue for this, but since I haven't changed any code I didn't think it needed an issue 😄 
Remove typos and weird syntax in README.
None.
None.
None.
=> cleaning up the README (no issue)

pages/_app.tsx, pages/api/searchresults/[type].js
=> Add logs to production

.env.production, pages/_app.tsx, pages/_document.tsx
=> fix IS PRODUCTION env var

components/RichTextOptions/BlogPostEmbed.tsx, helpers/_contentfulRichTextOptions.tsx, helpers/_date.tsx, package.json
=> Rich text options

.env.production, .env.staging
=> update blog env var

next.config.js
=> fix rewrite with new blog url env var

.env.staging, components/Layout/Layout.tsx
=> Add nofollow staging env

components/Forms/Contact/ContactForm.tsx, components/Forms/Inputs/Inputs.tsx, components/Forms/Subscribe/SubscribeForm.tsx, package-lock.json, package.json
Fork of PR #167 with fixed merged conflict from npm packages updates.
=> Iss 139 upgrade hooks form

public/robot.txt
=> add block to most common bot

components/Forms/Inputs/Inputs.tsx, pages/api/searchresults/[type].js
=> Merge devlop

package-lock.json, public/robot.txt
=> add sitemap and disallow /search in robot
